min_score: 50
min_descendants: 20

title_rules:
  - match_type: "word"
    ignore_case: true
    keywords: ["AI", "LLM", "gpt", "MCP", "AGI", "RAG", "CoT", "AIGC", "TRAE", "cursor"]
  
  - match_type: "contains"
    ignore_case: true
    keywords: ["deepseek", "kimi","Moonshot", "qwen", "minimax", "llma", "grok", "antropic", "gemini", "glm", "openai", "chatgpt", "claude", "openclaw", "opencode", "agentic", "ai agent", "Prompt Engine", "Multi-Agent", "Large Language Model", "Mistral", "prompt injection"]
